fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%env(mailer_user)%"
        sender_name: "%env(mailer_user)%"
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: email/password_resetting.email.twig
            from_email:
                address: "%env(mailer_user)%"
                sender_name: "%env(mailer_user)%"